import { Ticket, TicketMessage } from '../models/fixify.models';

const HOUR = 3600_000;
const DAY = 24 * HOUR;

function img(seed: string, name: string) {
  return {
    id: `att-${seed}`,
    url: `https://picsum.photos/seed/${seed}/900/560`,
    name,
    kind: 'image' as const,
  };
}

/**
 * Static mock tickets used to demo the AWS-style conversational ticketing module.
 * Each ticket has an accompanying conversation in MOCK_TICKET_MESSAGES, and most
 * problems include screenshot attachments.
 */
export const MOCK_TICKETS: Ticket[] = [
  {
    id: 'TK-2041',
    title: 'Checkout button unresponsive on mobile Safari',
    site: 'shop.brndynamics.com',
    customerName: 'BRN Dynamics',
    custId: 1,
    type: 'Bug',
    pri: 'critical',
    status: 'inprogress',
    who: 'Fixify Support',
    ago: '2h ago',
    createdAt: Date.now() - 2 * HOUR,
    desc: 'Customers on iPhone (Safari) report that tapping "Place Order" does nothing. Works on desktop. Screenshots attached from two affected devices.',
  },
  {
    id: 'TK-2038',
    title: 'Homepage LCP regressed to 4.8s after theme update',
    site: 'brndynamics.com',
    customerName: 'BRN Dynamics',
    custId: 1,
    type: 'Performance',
    pri: 'high',
    status: 'open',
    who: 'Unassigned',
    ago: '6h ago',
    createdAt: Date.now() - 6 * HOUR,
    desc: 'Since the last theme update our Largest Contentful Paint jumped from ~2.1s to 4.8s on the homepage. PageSpeed report attached.',
  },
  {
    id: 'TK-2027',
    title: 'SSL certificate expiry warning in browser',
    site: 'portal.acmecorp.io',
    customerName: 'Acme Corp',
    custId: 2,
    type: 'Security',
    pri: 'critical',
    status: 'resolved',
    who: 'Fixify Support',
    ago: '2d ago',
    createdAt: Date.now() - 2 * DAY,
    desc: 'Visitors are seeing a "Your connection is not private" warning. The certificate appears to have expired. Screenshot attached.',
  },
  {
    id: 'TK-2019',
    title: 'Contact form submissions not arriving in inbox',
    site: 'acmecorp.io',
    customerName: 'Acme Corp',
    custId: 2,
    type: 'Bug',
    pri: 'medium',
    status: 'open',
    who: 'Unassigned',
    ago: '1d ago',
    createdAt: Date.now() - 1 * DAY,
    desc: 'Leads submitted through the contact form are no longer reaching sales@acmecorp.io. No errors shown to the user.',
  },
  {
    id: 'TK-2004',
    title: 'Request: add Yoast SEO sitemap to robots.txt',
    site: 'brndynamics.com',
    customerName: 'BRN Dynamics',
    custId: 1,
    type: 'SEO',
    pri: 'low',
    status: 'closed',
    who: 'Fixify Support',
    ago: '5d ago',
    createdAt: Date.now() - 5 * DAY,
    desc: 'Could you reference our XML sitemap in robots.txt so crawlers pick it up faster?',
  },
];

export const MOCK_TICKET_MESSAGES: Record<string, TicketMessage[]> = {
  'TK-2041': [
    {
      id: 'm-2041-1',
      ticketId: 'TK-2041',
      authorName: 'BRN Dynamics',
      authorRole: 'customer',
      body: 'Customers on iPhone (Safari) report that tapping "Place Order" does nothing. It works fine on desktop Chrome. Here are screenshots from two affected devices.',
      ago: '2h ago',
      createdAt: Date.now() - 2 * HOUR,
      attachments: [img('checkout-mobile-a', 'iphone-safari-checkout.png'), img('checkout-mobile-b', 'ipad-checkout.png')],
    },
    {
      id: 'm-2041-2',
      ticketId: 'TK-2041',
      authorName: 'Fixify Support',
      authorRole: 'agent',
      body: 'Thanks for the detailed report and screenshots. We reproduced this on iOS Safari 17 — a recent plugin update is throwing a JS error that blocks the click handler. We are preparing a fix now.',
      ago: '1h ago',
      createdAt: Date.now() - 1 * HOUR,
      attachments: [img('checkout-console', 'safari-console-error.png')],
    },
    {
      id: 'm-2041-3',
      ticketId: 'TK-2041',
      authorName: 'Fixify Support',
      authorRole: 'system',
      body: 'Status changed to In Progress by Fixify Support.',
      ago: '1h ago',
      createdAt: Date.now() - 1 * HOUR + 60_000,
      attachments: [],
    },
  ],
  'TK-2038': [
    {
      id: 'm-2038-1',
      ticketId: 'TK-2038',
      authorName: 'BRN Dynamics',
      authorRole: 'customer',
      body: 'Since the last theme update our LCP jumped from ~2.1s to 4.8s on the homepage. Attaching the PageSpeed report.',
      ago: '6h ago',
      createdAt: Date.now() - 6 * HOUR,
      attachments: [img('pagespeed-report', 'pagespeed-homepage.png')],
    },
  ],
  'TK-2027': [
    {
      id: 'm-2027-1',
      ticketId: 'TK-2027',
      authorName: 'Acme Corp',
      authorRole: 'customer',
      body: 'Visitors are seeing a "Your connection is not private" warning. Looks like the certificate expired. Screenshot attached.',
      ago: '2d ago',
      createdAt: Date.now() - 2 * DAY,
      attachments: [img('ssl-warning', 'ssl-expired-warning.png')],
    },
    {
      id: 'm-2027-2',
      ticketId: 'TK-2027',
      authorName: 'Fixify Support',
      authorRole: 'agent',
      body: 'Confirmed — the auto-renewal hook had been disabled. We reissued and installed a fresh certificate, then forced a renewal cron so this will not recur.',
      ago: '2d ago',
      createdAt: Date.now() - 2 * DAY + 2 * HOUR,
      attachments: [img('ssl-fixed', 'valid-certificate.png')],
    },
    {
      id: 'm-2027-3',
      ticketId: 'TK-2027',
      authorName: 'Acme Corp',
      authorRole: 'customer',
      body: 'Verified on my end, the padlock is back. Thank you for the quick turnaround!',
      ago: '2d ago',
      createdAt: Date.now() - 2 * DAY + 3 * HOUR,
      attachments: [],
    },
    {
      id: 'm-2027-4',
      ticketId: 'TK-2027',
      authorName: 'Fixify Support',
      authorRole: 'system',
      body: 'Status changed to Resolved by Fixify Support.',
      ago: '2d ago',
      createdAt: Date.now() - 2 * DAY + 3 * HOUR + 60_000,
      attachments: [],
    },
  ],
  'TK-2019': [
    {
      id: 'm-2019-1',
      ticketId: 'TK-2019',
      authorName: 'Acme Corp',
      authorRole: 'customer',
      body: 'Leads submitted through the contact form are no longer reaching sales@acmecorp.io. The form shows a success message to the user though.',
      ago: '1d ago',
      createdAt: Date.now() - 1 * DAY,
      attachments: [img('contact-form', 'contact-form-success.png')],
    },
  ],
  'TK-2004': [
    {
      id: 'm-2004-1',
      ticketId: 'TK-2004',
      authorName: 'BRN Dynamics',
      authorRole: 'customer',
      body: 'Could you reference our XML sitemap in robots.txt so crawlers pick it up faster?',
      ago: '5d ago',
      createdAt: Date.now() - 5 * DAY,
      attachments: [],
    },
    {
      id: 'm-2004-2',
      ticketId: 'TK-2004',
      authorName: 'Fixify Support',
      authorRole: 'agent',
      body: 'Done — added "Sitemap: https://brndynamics.com/sitemap_index.xml" to robots.txt and submitted it in Search Console. Closing this out, reopen anytime if you need anything else.',
      ago: '5d ago',
      createdAt: Date.now() - 5 * DAY + 4 * HOUR,
      attachments: [],
    },
    {
      id: 'm-2004-3',
      ticketId: 'TK-2004',
      authorName: 'Fixify Support',
      authorRole: 'system',
      body: 'Status changed to Closed by Fixify Support.',
      ago: '5d ago',
      createdAt: Date.now() - 5 * DAY + 4 * HOUR + 60_000,
      attachments: [],
    },
  ],
};
